[package]
name = "andrew_johnson_wasm_game_of_life"
version = "0.1.0"
authors = ["Andrew <andrew@subarctic.org>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.63"

[dev-dependencies]
wasm-bindgen-test = "0.3.13"

[profile.release]
opt-level = "s"
